# Generated by Django 5.2.5 on 2025-08-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='cnic',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
