# Generated by Django 5.2.5 on 2025-08-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='towns_projects.town'),
        ),
    ]
