# Generated by Django 5.2.5 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns_projects', '0002_project_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
